version: '3.7'

services:

  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      - ADV_HOST=127.0.0.1
      - RUNTESTS=0
      - FOWARDLOGS=0
      - SAMPLEDATA=0
    ports:
      - 2181:2181
      - 3030:3030
      - 9581-9585:9581-9585
      - 9092:9092